### ISSUE TITLE
General improvements

### ISSUE THREAD

**Issue by Azecko** [Azecko/dossier-formation#17]
As @ponsfrilus said :

`je vois que bootstrap fait que le bord des tables est noir, c'est bizarre en bas de la première colonne.`
`je pense pas qu'il soit nécessaire d'avoir 2 titres en haut, seul dossier de formation de prénom nom est nécessaire`
`je serais pour mettre un peu de blah blah en haut du document, par exemple, comme dans le PDF`

**Comment by ponsfrilus** [comment]
Hey @Azecko look, checkboxes :)
- [x] bootstrap fait que le bord des tables est noir, c'est bizarre en bas de la première colonne.
- [x] pas qu'il soit nécessaire d'avoir 2 titres en haut, seul dossier de formation de prénom nom est nécessaire
- [x] mettre un peu de blah blah en haut du document, par exemple, comme dans le PDF

**Comment by ponsfrilus** [comment]
See #22

**Comment by ponsfrilus** [comment]
See #25

**Comment by ponsfrilus** [comment]
@Azecko issues have been reported in dedicated entries.
