### ISSUE TITLE
[fix] simplify the title

### ISSUE THREAD

**Issue by ponsfrilus** [Azecko/dossier-formation#25]
The main `<h1>` title of the page containing "Dossier Formation" should appear once.
The default value might be something like "Dossier Formation Prénom Nom (changez-moi)" or something similar.

It makes me think about the `<title>` tag of the page, that might be changed as well.

**Comment by Azecko** [comment]
closed by 756dab59e57e11287da805c3cd9046e6aecadd28 and 852457f917f49e00c8bd7a7e8a7b1c468c84222f
